package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.RadioButton;

import javafx.scene.control.CheckBox;

public class SampleController2 {
	@FXML
	private Button submit;
	@FXML
	private TextField name;
	@FXML
	private ComboBox mentorClass;
	@FXML
	private CheckBox C;
	@FXML
	private CheckBox Cplusplus;
	@FXML
	private CheckBox Csharp;
	@FXML
	private CheckBox Java;
	@FXML
	private CheckBox Python;
	@FXML
	private CheckBox VB;
	@FXML
	private RadioButton male;
	@FXML
	private RadioButton female;

	// Event Listener on Button[#submit].onAction
	@FXML
	public void addResponse(ActionEvent event) {
		// TODO Autogenerated
	}
}
