package application;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ComboBox;

import javafx.scene.control.RadioButton;
import java.util.*;
import java.net.*;
public class SampleController implements Initializable{
	@FXML
	private Button submit;
	@FXML
	private TextField name;
	@FXML
	private CheckBox C;
	@FXML
	private CheckBox Cplusplus;
	@FXML
	private CheckBox Csharp;
	@FXML
	private CheckBox Java;
	@FXML
	private CheckBox Python;
	@FXML
	private CheckBox VB;
	@FXML
	private RadioButton male;
	@FXML
	private RadioButton female;

	// Event Listener on Button[#submit].onAction
	@FXML
	public void addResponse(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	private ObservableList<String> classes = FXCollections.observableArrayList("M18301", "M18302", "M18303", "M18304", "M18305", "M18306", "M18307");
	@FXML
	private ComboBox mentorClass;
	public void initialize(URL url, ResourceBundle rb) {
		mentorClass.setItems(classes);
	}
}
